# This workflow will run tests and publish if needed the package to npm
#

name: CI

defaults:
  run:
    shell: bash

on: push

jobs:
  test-and-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
          java-package: 'jre'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: curl https://www.antlr.org/download/antlr-4.8-complete.jar -o ./antlr.jar
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Save build
        uses: actions/upload-artifact@v1
        with:
          name: brmslinter-bin
          path: bin/
  publish-npm:
    needs: test-and-build
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - name: Restore saved build
        uses: actions/download-artifact@v1
        with:
          name: brmslinter-bin
          path: bin
      - run: ./scripts/publish-if-needed.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
